### PR TITLE
Add Better Chatting compatibility

### PR DESCRIPTION
**Pull request by PennyJim**
I've implemented a single function that should safely print to Better Chatting's interface. There's more files with prints that need get swapped, but this is more so a proposal than my serious attempt at thoroughly making it compatible.
Hence why I'm making it a draft.

### CODE REVIEW

**Comment by Oarcinae** [comment]
@PennyJim Sorry for the slow reply, honestly looks fine to me! I can take it from here if you want, or you're welcome to finish it up yourself, either way is fine. Not sure when I'll get time to add this in, but hopefully in the next week or 2.

**Comment by PennyJim** [comment]
I can do it (if I remember). Shouldn't take me more than maybe an hour.

It really is just ctrl-f'ing for every print and replacing them with the compat send, so it'd not be hard for you if you feel like doing it before I remember to.

**Review by PennyJim — COMMENTED** [review]
Finally remembered to do it :D

**Comment by Oarcinae** [comment]
@PennyJim Do I need to set your mod as an optional dependency or anything else?

**Comment by PennyJim** [comment]
You can if you want to signify that you're compatible, but load order <ins>shouldn't</ins> matter here. All remote interfaces *have* to be created during the main chunk (before any events fire).

**Comment by Oarcinae** [comment]
Awesome, thanks for the help!

**Pull request merged**
